# Generated by Django 6.0.4 on 2026-05-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
